
server:
port: 8080

spring:
datasource:
name: customer_user
url: jdbc:mysql://127.0.0.1:3306/customer_user
username: root
password: root
driver-class-name: com.mysql.jdbc.Driver

mybatis:
mapper-locations: classpath:mapper/*.xml  #注意：一定要对应mapper映射xml文件的所在路径
type-aliases-package: com.example.demo1.entity  # 注意：对应实体类的路径
